### ISSUE TITLE
Add Lambda permissions on Lambda Deploy using link configuration

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3#118]
Currently lambda invoke permissions for an API Gateway deployment are applied as part of the API Gateway solution deployment. This means that if you recreate the Lambda function the permissions are lost and have to be applied manually 

Instead the permission should be applied as part of the lambda deployment and the API Gateway attributes are passed to the permissions via a link configured on the Lambda function.

**Comment by ml019** [comment]
As I'm refactoring the occurrence/link stuff at the moment, I'll have a go at this. Thanks for the issue @roleyfoley

**Comment by ml019** [comment]
The links will represent different things - link on api gateway to lambda represent functions that can be invoked, link to api-gateway on lambda represents gateways than can invoke the function.

they should be the same but the latter is not always needed depending on the authorisation model being employed

**Comment by ml019** [comment]
Closing as merged - "Fixes" comment got lost in the squashing
