### ISSUE TITLE
Remove contents of API Gateway Doc S3 bucket on deletion

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3#121]
PBI https://github.com/codeontap/codeontap/issues/23
When an API Gateway is removed the S3 bucket needs to be emptied otherwise the cloudformation script fails and the content of the docs s3 bucket has to be cleared manually.

Since the contents of this bucket are completely created at run time, they can just be deleted.

**Comment by ml019** [comment]
Job for the prologue script I think.

**Comment by roleyfoley** [comment]
This has been fixed as part of https://github.com/codeontap/gen3/pull/545

Thanks @ml019
