### ISSUE TITLE
Package gen3 in a docker container

### ISSUE THREAD

**Issue by ml019** [codeontap/gen3#130]
Epic https://github.com/codeontap/codeontap/issues/14

In order to simplify the management of generation framework versions, and to make it easier for multiple versions to be used across products and environments, template generation will now be done inside a docker container. As with other docker images in codeontap, it will accept a workspace via an "indir" directory, and any output will be generated in an outdir (typically mapped to a temporary directory).

For now the docker images should use a java base image to support freemarker. We will include any basic tools the gen3 scripts use, such as dos2unix. Later we can add things like Terraform.

There will be a dockerhub entry for gen3, with builds triggered by new tags on the gen3 repo. Minor releases will happen on a regular cycle (initially every three months). These correspond to the "train" idea that Spotify discuss on their videos.

New version releases will be offset to calendar quarters to avoid December/June periods (Christmas, EOFY)  1-February, 1-May, 1-August, 1-November.

We will also have weekly "candidate" releases. They will reflect the next minor release.

So assuming 5.6.0 is released on 1-May, the weekly releases will then be 5.7.0-rc1, 5.7.0-rc2 ... until 1-August when 5.7.0 will be released.  During a three monthly period, emergency patches on the last "train" will increment the patch level e.g. 5.6.1.

**Comment by ml019** [comment]
@roleyfoley does this align with your understanding of our discussion?

**Comment by roleyfoley** [comment]
Yep this sounds right. I had done a quick write up on it last week ( forgot to put it up) 

https://github.com/roleyfoley/codeontap/blob/development/Source/versioning.md

**Comment by roleyfoley** [comment]
First round of the docker containers are now in place and the images are stored here: 
https://github.com/codeontap/docker-gen3 

There are two containers which have been setup: 
- **base** - https://hub.docker.com/r/codeontap/gen3/ - This is an all in one image which includes the build and management tools required for our current automation server setup. The intention with the first round of the container is to include everything that the automation server requires to build and deploy our range of products 
  - User: root
  - WorkDir: /var/opt/codeontap 
- **jenkins-jnlp-slave** - https://hub.docker.com/r/codeontap/gen3-jenkins-slave/ - Uses the base image but also adds the necessary components and entry points required for the container to run as Jenkins JNLP slave
  - User: jenkins 
  - WorkDir: /home/jenkins

**Comment by roleyfoley** [comment]
In Docker hub we use automated builds to keep all of the containers up to date, they have the following triggers 

| Docker Image | Trigger Source | Trigger Property | Docker Tag | 
| ------------- | ------------- | ------------- | ------------- |
| codeontap/gen3 | Github docker-gen3 | master branch | stable | 
| codeontap/gen3 | github  docker-gen3  | development branch | latest | 
| codeontap/gen3 | github docker-gen3 | tag | same as tag | 
| codeontap/gen3-jenkins-slave | Dockerhub | dockerimage codeontap/gen3 | All Images | 
| codeontap/gen3 | Github Web Hook  | push event |  All Images | 

So what this essentially means is that builds of the base image are triggered whenever changes are made to the core codeontap repos (gen3, gen3-automation, gen3-startup) or changes are made to the docker image configuration. Any of these builds will then trigger the jenkins slave image to be built.

**Comment by roleyfoley** [comment]
The base image can be used like a client at the moment, the standard environment variables (GENERATION_DIR, AUTOMATION_DIR etc ) are all set. All you need to do is either clone the CMDB's in to the container or clone them on your host machine and mount them as a volume to /var/opt/codeontap. 

Once this is done you just need to set the ENV variable for the account you want to work in ( like you would normally at the moment) 

AWS credentials also need to be set if you are using AWS from the container.

**Comment by roleyfoley** [comment]
Epic https://github.com/codeontap/codeontap/issues/14

**Comment by roleyfoley** [comment]
Confirmed that container builds are now working and tagging process in place.
