### ISSUE TITLE
Add support for controlling RDS minor release upgrade policy

### ISSUE THREAD

**Issue by ml019** [codeontap/gen3#139]
Add a configuration setting to control whether minor version upgrades are permitted in the maintenance window.

Support a per environment default, with it turned off in production environments and enabled otherwise.

**Comment by ml019** [comment]
hmm - ok just reread my issue and can see why you made the changes you did. I'll need to update my review

**Comment by roleyfoley** [comment]
@ml019 and @kshychko 
Can this be closed off now?

**Comment by ml019** [comment]
Yep.
