### ISSUE TITLE
Remove deprecated "slice" switch (-s)

### ISSUE THREAD

**Issue by ml019** [codeontap/gen3#14]
Remove the deprecated -s switch from createTemplate.sh and managestacks.sh

**Comment by roleyfoley** [comment]
@ml019 Is this still required?

**Comment by ml019** [comment]
Is switch still there? Probably time to remove and deal with th fallout

**Comment by roleyfoley** [comment]
Looks like its been overriden 

-s is an alternative of -u ( Deployment Unit)  
-t is an alternative of -l ( Level ) 

Do we want to remove it completely?

**Comment by RossMurr4y** [comment]
Getting to this late I know but I replaced -s in manageDeployment with "subscription". Worth noting in case we end up merging these scripts for whatever reason.
