### ISSUE TITLE
Remove .sh prefix on scripts

### ISSUE THREAD

**Issue by ml019** [codeontap/gen3#15]
Best practice bash scripting suggests scripts shouldn't have an extension.

**Comment by roleyfoley** [comment]
@ml019 Do we still want to do this? Feels like it would get confusing with the mix of languages in the repos...

**Comment by ml019** [comment]
Yup - lets close this for now. We still need to re-org all the scripts and if they end up in shell specific subdirs, then we could consider removing .sh to align with best practice.
