### ISSUE TITLE
Subcomponent setting Hash value in Environment Varaiables

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3#190]
When processing environment variables for Lambda and ECS the environment variable for the Subcomponent is currently being set as a hash 

````json 
            "Environment": [
              {
                "Name": "SUBCOMPONENT",
                "Value": {
                  "Id": "app",
                  "Name": "app"
                }
              },
````

the environment variables can only be set to string so this is causing a failure

**Comment by roleyfoley** [comment]
Added PR #189  to use the name value for the subcomponent.

**Comment by ml019** [comment]
PR #189 is good and merged. Closing issue
