### ISSUE TITLE
Add automated password encryption during deployment

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3#207]
For services like RDS, the master password has to be provided in a clear text format within the Cloudformation template. Given that we store cloudformation templates in a repository this is not following security best practices. 

Instead we should look at an alternate way to do the following: 
- Generate a Password and encrypt it using KMS
- Set a dummy password in the cloudformation template 
- Update the password in using the generated password

**Comment by roleyfoley** [comment]
Turning this in to a framework process would be 

1.  A prologue script which generates a password, encrypts the password using KMS then stores that as a psuedo stack output. 
2. A cloudformation template is generated with a dummy password set. The cloudformation template never sets a real password 
3. An epilogue script then resets the password using the details from the pseudo stack output

**Comment by ml019** [comment]
The epilogue script would also generate a pseudo stack of the complete URL to the db (including credentials) encrypted using KMS.

This way the app has the choice of individual variables and assemble the URL itself, or a one ready for the microwave. Both will be exposed via the attributes of the component.

**Comment by roleyfoley** [comment]
Reopening as the URL still needs to be encrypted

**Comment by roleyfoley** [comment]
The URL could be tricky to build and encrypt. The RDS hostname value is generated at build time and includes a random string that we wouldn't know.  

So this leaves a couple of options 
- To get the URL the RDS solution needs to be run twice, this doesn't really feel like a perfect solution more a workaround
- Find away to pass a stack output to an epilogue script so that the value can be used. 
  - Leaving the stack output files in a tmp directory that the epilogue script could look through?

**Comment by roleyfoley** [comment]
Another alternative could be to create a CNAME record with a domain name we generate in the template process. 
AWS Route53 documentation suggests this could be useful for database replacements as well 
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-rds-db.html

**Comment by roleyfoley** [comment]
URL encryption now added, the build references are already updated between the template run and the epilogue run so its easy to get the endpoint FQDN 

PR https://github.com/codeontap/gen3/pull/262 fixes this and adds an encrypted URL pseudo stack. 

GenerateCredentials must be enabled for this to work.
