### ISSUE TITLE
Add Reference Documentation details to Component Configuration

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3#257]
PBI https://github.com/codeontap/codeontap/issues/20
With the move to occurrences we now create a component configuration hash which contains all of the component level configuration parameters that are available. 

This has a built in structure already with defined properties 
- Name
- Default
- Children

These values essentially form the basis of reference documentation which can be used to build out documentation. Since our code is a templating language we could extend this object and create a new template which creates reference documentation of our components. 

I would initially suggest we add the following extra properties 
- Description - One line description of what the property does 
- Possible Values - an array of values that are available, could also be used to validate at run time 
- Range - extension of Possible values for integer based values

**Comment by ml019** [comment]
In general I see most things having an id, name, title and description. OS I'd suggest thinking about a title as well - one line summary of description basically.

Re possible values, probably need some specific attributes for different possibilities e.g. enumeration, regex etc.

**Comment by roleyfoley** [comment]
Suggested structure for component properties 

```json 
{
   "Name"   : "<property name>",
   "Title"  : "<short description>",
   "Description" : "<long description",
   "Value" :  {
        "Default"   : "<default value>",
        "Required"  : "true|false",
        "Possible"  : ["<Array of possible values>"],
        "Pattern"   : "<regex pattern to match>",
        "Range"     : "<int range>"
    },
    "Children"  : [ "<A collection of Property objects>" ],
    "Default"   : "<backwards compatibility for existing value>"
} 
```

I think this format would fit most cases that we have, all of it could be done using the Pattern property but from a documentation perspective it would probably be nicer to read from the Range, possible values than regex.

**Comment by ml019** [comment]
I'd use "Enumeration" instead of "Possible"

We should think about how to turn this into a json schema so we can schema validate the input.

Also this requires default and required to be moved in current configs.

Also name can actually be an array with the first entry the preferred value but the others accepted as well

**Comment by roleyfoley** [comment]
This has now been setup and we are generating reference documentation on https://codeontap.readthedocs.io/en/stable/reference/component-reference/
