### ISSUE TITLE
Blueprint Generation - Remove Occurrence Deployment Check

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3#283]
At the moment the blueprint filters out occurrences that have not had any resources deployed to them. The deployed flag is determined by performing a getExistingReference on the resources, since some resources do not have references save ( application level templates, scripts, etc) this isn't a true representation of what has been deployed. 

Instead the blueprint should show everything that has been deployed and we should grey out occurrences that have been disabled for deployment.

**Comment by ml019** [comment]
Looks like this got fixed in https://github.com/codeontap/gen3/pull/284.

Can this issue be closed?
