### ISSUE TITLE
Add Data Pipeline Component Support

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3#410]
PBI https://github.com/codeontap/codeontap/issues/31
AWS Data pipelines provide an automated data management process which manages moving data between different formats. A pipeline is a workflow definition which can provision, run and deprovision different AWS resources on the fly to transform data. 

https://aws.amazon.com/datapipeline/

**Comment by roleyfoley** [comment]
From the AWS getting started guide a pipeline is 

> To use AWS Data Pipeline, you create a pipeline definition that specifies the business logic for your data processing. A typical pipeline definition consists of activities that define the work to perform, data nodes that define the location and type of input and output data, and a schedule that determines when the activities are performed. 

In terms of codeontap design the pipeline definition would be similar to a API Gateway swagger definition, the developer of the pipeline would write their definition along with any code that might be required. Codeontap would take that definition add in the environment specific configuration and they deploy the pipeline.

**Comment by roleyfoley** [comment]
A pipeline would be linked to data objects with 2 roles 
  - Input 
  - Output 

Input linked objects would be provided to the pipeline as INPUT_<Details> parameters and output objects OUTPUT_<Details> parameters 

The pipeline can be triggered in a couple of different ways
  - Scheduled trigger ( a time based trigger) 
  - A link based trigger, this would be a lambda event trigger that activates the pipeline. This lambda could be triggered by an S3 update, log event, container, or even another lambda.

**Comment by STOIE** [comment]
Hey Mike,

The issue we have at the moment is that for our first use case, the output is actually a snapshot from a PG RDS instance (which is the output in pipeline talk).
So for the general pipeline this works, but the issue I have is that we don't want the RDS instances to remain standing (due to cost reasons) - we want them to only exist dependant on the pipeline itself.
Noting that, RDS is considered the pipelines output, you cannot exec an RDS instance to be stood up from within the pipeline itself (from what I have been able to find so far).

**Comment by roleyfoley** [comment]
@STOIE This was my thoughts on that https://github.com/codeontap/gen3/issues/409 
It might be a little complicated but it would achieve what we are trying to do I think

**Comment by monkeypants** [comment]
@roleyfoley can you give me an update on this please.

**Comment by monkeypants** [comment]
After that merge, can we close this ticket?

**Comment by roleyfoley** [comment]
Data pipeline has now been deployed and validated
