### ISSUE TITLE
Data Component : S3 Directory

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3#425]
Data components allow for data to be treated like code deployments in codeontap. The data component manages the data build references and the staging of different versions of the data.

This task is to add data components to initally manage the data references for s3 uploaded data.

**Comment by monkeypants** [comment]
What's the status of this @roleyfoley ?

**Comment by roleyfoley** [comment]
Haven't started it yet

**Comment by roleyfoley** [comment]
So the requirements with an S3 data object is to essentially manage and S3 data like we do a code registry at the moment. With a code registry we store the build artefacts of each commit in its own directory. I think we would treat S3 data in the same way 

An S3 data component would have a master prefix where the data is uploaded. This prefix is hosted in the app-data bucket of the environment. A build job lists the contents of the master prefix and collects the ETags that are generated for each file. These are written as a JSON file cot_data_file_manifest.json
```
{ 
   "fileName" : <file relative to the master prefix>,
   "eTag" : <the etag of the file> 
} 
``` 

Once this file has been created it is hashed and that becomes the build reference for an s3 data object. 

The master  data folder is then copied to the accounts registry bucket based on its component name and the hash of the manifest file like we do for code currently. 

This does lead to duplication of data but ensures that we can replay data and migrate data like we do with code. We can also enable S3 lifecycle policies to reduce the data costs.

When a component links to the data component it receives the bucket URL for the latest build reference in the registry bucket.

During the prepare of a release the selected data prefix is copied to the registry that requires it. We would need to enable cross account access for S3 buckets to stop us having to download the data to the automation server and then copying it back up. 

This could be a setting on each account on which accounts to share the registry with. 

@ml019 what do you think of this approach?
