### ISSUE TITLE
Data Component : RDS Snapshot

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3#426]
Following on from #425 we also need to manage RDS snapshots in a similar way to S3 data. An RDS data object will look after sharing and copying RDS snapshots between environments and between updates

**Comment by roleyfoley** [comment]
An RDS data component would work in a similar fashion to #425 but instead of S3 references we would use snapshot naming to manage the process. 

A RDS data component would have a designated snapshot name for its master snapshot 
```
<component name>_master
```

If a snapshot is created or copied into the integration with this account and a build is run the build job gets the SnapshotCreateTime of the snapshot, hashes it and this becomes the build reference. The snapshot is then copied with the name <component name>_<build reference>. 

ManageImage then copies the snapshot to the appropriate account. Again we would need to enable a default sharing configuration for snapshots to share a snapshot between the appropriate accounts since they can not be downloaded, only copied around the place. 

@ml019 does that sound reasonable?

**Comment by roleyfoley** [comment]
To use these snapshots we would introduce an application level RDS component, a data set which when linked to an application component uses this as it snapshotID on every build. If this changes the cloudformation process will force the database to be restored from the data set snapshot.

**Comment by ml019** [comment]
Sounds reasonable to me.

**Comment by roleyfoley** [comment]
Implemented using the existing RDS solution component. Its a two stage process at the moment. 
You promote the application level dataset 
link the solution rds instance to the dataset 

run a manage environment to restore the rds instance with the new snapshot version

This also has the benefit of being able to perform blue/green updates with restorations to two instance
