### ISSUE TITLE
Network - Remove support for eipvpc and eips3vpc units in eip/vpc support

### ISSUE THREAD

**Issue by ml019** [codeontap/gen3#690]
With all customers now on a relatively current version of cot, these two units can be removed. They were there for backwards compatibility but there's no deployments to be compatible with anymore.

**Comment by ml019** [comment]
@roleyfoley I think this issue can be closed? The units are no longer mentioned in the code base as I think they were addressed as part of the refactoring of vpcs with https://github.com/codeontap/codeontap/issues/24?

**Comment by ml019** [comment]
@roleyfoley thoughts?

**Comment by roleyfoley** [comment]
Last couple of PR's clean that up this should close this off

**Comment by ml019** [comment]
Closing as complete as  result of other refactors
