### ISSUE TITLE
Update Nat Segment Autoscale group for Security Updates

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3#86]
While we don't use EC2 based NAT Gateways anymore we would like to make sure that they are patched in the same way as the other instances. The same yum update security and cron job structure needs to be added to NAT EC2 scaling groups

https://github.com/codeontap/gen3/blob/822adfa26e552b4b20ed6fb6f0fd03913de2b01b/aws/templates/segment/segment_vpc.ftl#L652

**Comment by kshychko** [comment]
@roleyfoley can we close this?

**Comment by roleyfoley** [comment]
Nat configuration updated and confirmed that it is now the latest version,
